# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# This workflow configuration specifies that the unit test job should run on every push and pull request event.
# It runs on an Ubuntu environment and performs the following steps:

#   Checks out your repository code.
#   Sets up the Python environment.
#   Installs the dependencies specified in your requirements.txt file (if you have one).
#   Runs the unit test command python -m unittest test_daily_temperature_analysis.py.


name: Unit Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest test_daily_temperature_analysis.py

